name: Build & Deploy dist to 'dist' branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add CNAME
        run: echo "sensor.ecotwinai.com" > dist/CNAME

      - name: SPA 404 fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to 'dist' branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dist
          folder: dist
          clean: true
